export const SET_USER_INFO = 'SET_USER_INFO'
export const AUTH_ERROR = 'AUTH_ERROR'

export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN'
export const AUTH_LOGIN_SAGA = 'AUTH_LOGIN_SAGA'
export const AUTH_SIGNUP_SAGA = 'AUTH_SIGNUP_SAGA'
export const FETCH_USERDATA_SAGA = 'FETCH_USERDATA_SAGA'