export const SET_USER_INFO = 'SET_USER_INFO'
export const AUTH_ERROR = 'AUTH_ERROR'

// User
export const AUTH_USER_LOGIN = 'AUTH_USER_LOGIN'
export const AUTH_LOGIN_SAGA = 'AUTH_LOGIN_SAGA'
export const AUTH_SIGNUP_SAGA = 'AUTH_SIGNUP_SAGA'
export const FETCH_USERDATA_SAGA = 'FETCH_USERDATA_SAGA'
export const SET_USER_DATA = 'SET_USER_DATA'
export const UPDATE_USERDATA_TO_DB_SAGA = 'UPDATE_USERDATA_TO_DB_SAGA'
export const SET_USERDATA_TO_DB_SAGA = 'SET_USERDATA_TO_DB_SAGA'

// Project
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT' 
export const FETCH_USERPROJECTS_SAGA = 'FETCH_USERPROJECTS_SAGA'
export const SET_PROJECTS = 'SET_PROJECTS'

export const SET_ERROR = 'SET_ERROR'